### PR TITLE
Fix #35 updating dependencies

### LINKED ISSUE #35: jwe using Curve P521, ECDH-ES, and A256GCM does not always work with with other implementations
I am facing an issue where i can't validate with krakend-jose a JWT with a JWK issued by an auth provider (which issues JWT with an implem with pyjwt).
I think the bug is comming from square/go-jose : https://github.com/square/go-jose/issues/228
The bug was corrected in June 2019 and was ship in 2.4.0 but krakend-jose has go-jose 2.2.2 as a dependency.

### PR DESCRIPTION
**Pull request by neokeld**
Fix https://github.com/devopsfaith/krakend-jose/issues/35 updating dependencies (
- go list -m -u all
- go get -u
- go mod tidy
).

### CODE REVIEW

**Comment by neokeld** [comment]
@taik0 @kpacha this little PR is looking for reviewers :smile:

**Comment by kpacha** [comment]
Updating every dependency at once looks a little scary to me. I think it would be safer to upgrade just the square/go-jose package

**Comment by neokeld** [comment]
Done

**Comment by kpacha** [comment]
the build is broken... what other things are changed in the updated lib?

**Comment by neokeld** [comment]
As we can see in https://github.com/square/go-jose/issues/228 the encrypted result was inaccurate. I've corrected tests with signed values from output from square go-jose.

**Comment by kpacha** [comment]
thx for the contribution!

**Pull request merged**
