### PR TITLE
Mux

### PR DESCRIPTION
**Pull request by Foxcool**

### CODE REVIEW

**Comment by kpacha** [comment]
please, @Foxcool, check the merging conflicts.

thxs!

**Comment by Foxcool** [comment]
done!

**Comment by Foxcool** [comment]
Can't ensure here and on master branch

```
dep ensure -v
Root project is "github.com/devopsfaith/krakend-jose"
 3 transitively valid internal packages
 9 external packages imported from 4 projects
(0)   ✓ select (root)
(1)     ? attempt github.com/auth0-community/go-auth0 with 1 pkgs; 4 versions to try
(1)         try github.com/auth0-community/go-auth0@v1.0.0
(1)     ✓ select github.com/auth0-community/go-auth0@v1.0.0 w/1 pkgs
(2)     ? attempt github.com/devopsfaith/krakend with 5 pkgs; 13 versions to try
(2)         try github.com/devopsfaith/krakend@0.7.0
(2)     ✓ select github.com/devopsfaith/krakend@0.7.0 w/13 pkgs
(3)     ? attempt github.com/gin-gonic/gin with 1 pkgs; 21 versions to try
(3)         try github.com/gin-gonic/gin@v1.3.0
(3)     ✓ select github.com/gin-gonic/gin@v1.3.0 w/4 pkgs
(4)     ? attempt github.com/gin-contrib/sse with 1 pkgs; 1 versions to try
(4)         try github.com/gin-contrib/sse@master
(4)     ✓ select github.com/gin-contrib/sse@master w/1 pkgs
(5)     ? attempt github.com/ugorji/go with 1 pkgs; 5 versions to try
(5)         try github.com/ugorji/go@v1.1.2
(5)     ✓ select github.com/ugorji/go@v1.1.2 w/1 pkgs
(6)     ? attempt github.com/golang/protobuf with 1 pkgs; 7 versions to try
(6)         try github.com/golang/protobuf@v1.2.0
(6)     ✓ select github.com/golang/protobuf@v1.2.0 w/1 pkgs
(7)     ? attempt github.com/mattn/go-isatty with 1 pkgs; 6 versions to try
(7)         try github.com/mattn/go-isatty@v0.0.4
(7)     ✓ select github.com/mattn/go-isatty@v0.0.4 w/1 pkgs
(8)       ← no more versions of golang.org/x/sys to try; begin backtrack
(7)     ← backtrack: no more versions of github.com/mattn/go-isatty to try
(6)     ← backtrack: no more versions of github.com/golang/protobuf to try
(5)     ← backtrack: no more versions of github.com/ugorji/go to try
(4)     ← backtrack: no more versions of github.com/gin-contrib/sse to try
(3)     ← backtrack: no more versions of github.com/gin-gonic/gin to try
(2)     ← backtrack: no more versions of github.com/devopsfaith/krakend to try
(1)     ← backtrack: no more versions of github.com/auth0-community/go-auth0 to try
  ✗ solving failed



```

**Comment by kpacha** [comment]
It's weird because it worked on travis just a week ago: https://travis-ci.org/devopsfaith/krakend-jose/builds/485104773

**Comment by Foxcool** [comment]
After drop dep cache it works. Good?

**Comment by kpacha** [comment]
@Foxcool I don't think exporting everything at the base package and having duplicated code between the `gin` and `mux` packages (like `canAccess` and `newValidator`) is the best option here...

**Comment by kpacha** [comment]
please, check my suggestions at https://github.com/Foxcool/krakend-jose/pull/1

**Comment by Foxcool** [comment]
hi, tests passed. Merged

**Comment by kpacha** [comment]
thxs for the contribution!

**Pull request merged**
